table DimCurrency
	lineageTag: f5dfb52a-e0e3-42a5-8ff4-e74edb1b0f33

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: f2237b0d-c78c-4d46-96db-29e5045b1a9c
		summarizeBy: count
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column CurrencyName
		dataType: string
		lineageTag: c5431de7-6340-4154-be21-da27049fde91
		summarizeBy: none
		sourceColumn: CurrencyName

		annotation SummarizationSetBy = Automatic

	column CurrencyDescription
		dataType: string
		lineageTag: bff3a025-f31a-4b63-b674-6c2c3dce98b2
		summarizeBy: none
		sourceColumn: CurrencyDescription

		annotation SummarizationSetBy = Automatic

	partition DimCurrency = m
		mode: import
		source =
				let
				  Source = Sql.Database("localhost\SQLEXPRESS", "ContosoRetailDW"),
				  #"Navigation 1" = Source{[Schema = "dbo", Item = "DimCurrency"]}[Data],
				    RemovedUnneccessaryColumns = Table.RemoveColumns(#"Navigation 1",{"ETLLoadID", "LoadDate", "UpdateDate", "FactExchangeRate", "FactInventory", "FactOnlineSales", "FactSales", "FactSalesQuota", "FactStrategyPlan", "CurrencyLabel"})
				in
				  RemovedUnneccessaryColumns

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

