table DimDate
	lineageTag: 63feb4ad-4888-41c7-9283-f5010f0d3014
	dataCategory: Time

	column Datekey
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: beb8e07c-7b15-4525-bf7b-113090779aab
		summarizeBy: none
		sourceColumn: Datekey

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CalendarYear
		dataType: int64
		formatString: 0
		lineageTag: 104058ef-da88-49e3-8c29-4dd5007aa9b3
		summarizeBy: none
		sourceColumn: CalendarYear

		annotation SummarizationSetBy = Automatic

	column CalendarYearLabel
		dataType: string
		lineageTag: aa2c5827-30b3-41f2-bb06-b52932b3eeaf
		summarizeBy: none
		sourceColumn: CalendarYearLabel

		annotation SummarizationSetBy = Automatic

	column CalendarHalfYear
		dataType: int64
		formatString: 0
		lineageTag: 8b300b59-5845-4a8b-8ca2-d2fad1ceaf73
		summarizeBy: none
		sourceColumn: CalendarHalfYear

		annotation SummarizationSetBy = Automatic

	column CalendarHalfYearLabel
		dataType: string
		lineageTag: fb128f18-9124-45a6-91f5-10f327199087
		summarizeBy: none
		sourceColumn: CalendarHalfYearLabel

		annotation SummarizationSetBy = Automatic

	column CalendarQuarter
		dataType: int64
		formatString: 0
		lineageTag: 9d625029-f5dd-4e47-9fa0-752e1d11cc18
		summarizeBy: none
		sourceColumn: CalendarQuarter

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterLabel
		dataType: string
		lineageTag: f981b4f7-e84f-47ca-9c1d-dd20450c4d3e
		summarizeBy: none
		sourceColumn: CalendarQuarterLabel

		annotation SummarizationSetBy = Automatic

	column CalendarMonth
		dataType: int64
		formatString: 0
		lineageTag: 68be22a8-c5e1-4075-be18-1271d0c279cc
		summarizeBy: none
		sourceColumn: CalendarMonth

		annotation SummarizationSetBy = Automatic

	column CalendarMonthLabel
		dataType: string
		lineageTag: fa76ef9b-c3d8-4d08-99f8-028795f383b1
		summarizeBy: none
		sourceColumn: CalendarMonthLabel

		annotation SummarizationSetBy = Automatic

	column CalendarWeek
		dataType: int64
		formatString: 0
		lineageTag: 7e2936c8-651d-4c8c-a432-fa18c4939024
		summarizeBy: none
		sourceColumn: CalendarWeek

		annotation SummarizationSetBy = Automatic

	column CalendarWeekLabel
		dataType: string
		lineageTag: 8210a3b0-7322-4272-9581-22c73c28e4e4
		summarizeBy: none
		sourceColumn: CalendarWeekLabel

		annotation SummarizationSetBy = Automatic

	column CalendarDayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: b341ecb0-9d5e-4f30-9082-8d4bcd3e6481
		summarizeBy: none
		sourceColumn: CalendarDayOfWeek

		annotation SummarizationSetBy = Automatic

	column CalendarDayOfWeekLabel
		dataType: string
		lineageTag: 4cc41ead-668d-46d3-96fb-e79517f798d9
		summarizeBy: none
		sourceColumn: CalendarDayOfWeekLabel

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: f956114f-795e-40c6-94dd-3bb28e25312d
		summarizeBy: none
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalYearLabel
		dataType: string
		lineageTag: ea192519-037c-490f-81d3-67e3476ec973
		summarizeBy: none
		sourceColumn: FiscalYearLabel

		annotation SummarizationSetBy = Automatic

	column FiscalHalfYear
		dataType: int64
		formatString: 0
		lineageTag: b127d833-54bf-4370-a577-f49143ce6185
		summarizeBy: none
		sourceColumn: FiscalHalfYear

		annotation SummarizationSetBy = Automatic

	column FiscalHalfYearLabel
		dataType: string
		lineageTag: 5c0d6d4f-4053-46c8-ada6-555581cfac59
		summarizeBy: none
		sourceColumn: FiscalHalfYearLabel

		annotation SummarizationSetBy = Automatic

	column FiscalQuarter
		dataType: int64
		formatString: 0
		lineageTag: f210dee0-49c9-457f-a6ee-712895d6dd2a
		summarizeBy: none
		sourceColumn: FiscalQuarter

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterLabel
		dataType: string
		lineageTag: 90438742-9a81-4405-8268-7036bf23f937
		summarizeBy: none
		sourceColumn: FiscalQuarterLabel

		annotation SummarizationSetBy = Automatic

	column FiscalMonth
		dataType: int64
		formatString: 0
		lineageTag: e3a589e4-d266-4460-9819-828f48d9fd9c
		summarizeBy: none
		sourceColumn: FiscalMonth

		annotation SummarizationSetBy = Automatic

	column FiscalMonthLabel
		dataType: string
		lineageTag: 1f2331cd-495b-4ef1-9a89-957877f4b4e6
		summarizeBy: none
		sourceColumn: FiscalMonthLabel

		annotation SummarizationSetBy = Automatic

	column IsWorkDay
		dataType: string
		lineageTag: a851661f-e712-4af6-9d9c-742561b81adf
		summarizeBy: none
		sourceColumn: IsWorkDay

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		dataType: int64
		formatString: 0
		lineageTag: 88d4ca62-2c0c-4aae-a6f0-55fbc7bd7ca0
		summarizeBy: none
		sourceColumn: IsHoliday

		annotation SummarizationSetBy = Automatic

	column HolidayName
		dataType: string
		lineageTag: 73bee86c-83ce-41ef-8643-80f88d3d6b57
		summarizeBy: none
		sourceColumn: HolidayName

		annotation SummarizationSetBy = Automatic

	column EuropeSeason
		dataType: string
		lineageTag: 644ba347-3e29-4972-9ffd-d6b438fc1199
		summarizeBy: none
		sourceColumn: EuropeSeason

		annotation SummarizationSetBy = Automatic

	column NorthAmericaSeason
		dataType: string
		lineageTag: 623f2044-6d6d-483f-bc4d-3d0cbf8dd1ea
		summarizeBy: none
		sourceColumn: NorthAmericaSeason

		annotation SummarizationSetBy = Automatic

	column AsiaSeason
		dataType: string
		lineageTag: 85457b79-c3b4-4b55-a679-d7a6825bedc6
		summarizeBy: none
		sourceColumn: AsiaSeason

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				  Source = Sql.Database("localhost\SQLEXPRESS", "ContosoRetailDW"),
				  #"Navigation 1" = Source{[Schema = "dbo", Item = "DimDate"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Navigation 1",{{"Datekey", type date}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"FullDateLabel", "DateDescription", "FactExchangeRate", "FactITMachine", "FactITSLA", "FactInventory", "FactOnlineSales", "FactSales", "FactSalesQuota", "FactStrategyPlan"})
				in
				  #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

